// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7VmLZ9g70vdfhUd53nUT5ScjjHRsBxhM',
    appId: '1:191851436679:web:44f8261da9b8b8d259b622',
    messagingSenderId: '191851436679',
    projectId: 'badgetestfirebase',
    authDomain: 'badgetestfirebase.firebaseapp.com',
    storageBucket: 'badgetestfirebase.appspot.com',
    measurementId: 'G-5TECHJMVYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWCP2Ex0amFF8xggp6LV2b2O7Hrl1SpM',
    appId: '1:191851436679:android:45a8087e78ecd56059b622',
    messagingSenderId: '191851436679',
    projectId: 'badgetestfirebase',
    storageBucket: 'badgetestfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCivnkwFjPyirA4ahwO_uumbN1IrnI9KY8',
    appId: '1:191851436679:ios:86cb5e3a535ec27259b622',
    messagingSenderId: '191851436679',
    projectId: 'badgetestfirebase',
    storageBucket: 'badgetestfirebase.appspot.com',
    iosBundleId: 'com.example.badgemachinetestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCivnkwFjPyirA4ahwO_uumbN1IrnI9KY8',
    appId: '1:191851436679:ios:dd3ce835b4738aee59b622',
    messagingSenderId: '191851436679',
    projectId: 'badgetestfirebase',
    storageBucket: 'badgetestfirebase.appspot.com',
    iosBundleId: 'com.example.badgemachinetestapp.RunnerTests',
  );
}
